#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/functions.php';

use Symfony\Component\Console\Application;
use NewInventor\ConfigTool\Config;

Config::init(__DIR__ . '/config');

$application = new Application();

$commands = Config::get('commands');
foreach ($commands as $command) {
    $application->add(new $command());
}

$application->run();